package view;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import control.ControlDados;

/**
 *
 * @author pablo
 */
public class TelaObra extends JPanel {
	private JLabel jLabel1;
	private JScrollPane jScrollPane2;
	private JTable tObras;
	private ControlDados d;

	/**
	 * Creates new form TelaObra
	 */
	public TelaObra(ControlDados dados) {
		d = dados;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new JLabel();
		jScrollPane2 = new JScrollPane();

		tObras = new JTable();

		setBackground(new java.awt.Color(255, 255, 255));
		setMinimumSize(new java.awt.Dimension(771, 300));
		setLayout(null);

		jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
		jLabel1.setText("Catalogo");
		jLabel1.setToolTipText("");
		add(jLabel1);
		jLabel1.setBounds(290, 10, 160, 40);

		tObras.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null }, { null, null, null, null, null, null },
						{ null, null, null, null, null, null }, { null, null, null, null, null, null } },
				new String[] { "ID", "Titulo", "Autor", "Edtora", "Edição", "Preço" }));
		tObras.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				tObrasMouseClicked(evt);
			}
		});
		jScrollPane2.setViewportView(tObras);

		add(jScrollPane2);
		jScrollPane2.setBounds(10, 60, 750, 240);
	}

	private void tObrasMouseClicked(java.awt.event.MouseEvent evt) {

	}

}